apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdA==  # base64 encoded password, e.g., 'password'
  mysql-username: cm9vdA==  # base64 encoded username, e.g., 'root'
  mysql-password: cm9vdA==  # base64 encoded password, e.g., 'password'
